let promptList = [{name: "Abominable Snowman", description: ""},
    {name: "Alien", description: ""},
    {name:"Ammit", description: ""},
    {name:"Angelic Abomination", description: ""},
    {name:"Animatronic", description: ""},
    {name:"Baba Yaga", description: ""},
    {name:"Banshee", description: ""},
    {name:"Bat Wings", description: ""},
    {name:"Beauty & the Beast", description: ""},
    {name:"Bedsheet Ghost", description: ""},
    {name:"Belly Mouth", description: ""},
    {name:"Bigfoot", description: ""},
    {name:"Black Widow", description: ""},
    {name:"Bloody Mary", description: ""},
    {name:"Boogie Man", description: ""},
    {name:"Brain"},
    {name:"Brain & Brawn"},
    {name:"Bugbear"},
    {name:"Butler/Maid"},
    {name:"Candle"},
    {name:"Candy Witch"},
    {name:"Cat"},
    {name:"Cenobite"},
    {name:"Chained"},
    {name:"Chimera"},
    {name:"Chupacabra"},
    {name:"Clockwork"},
    {name:"Cockatrice"},
    {name:"Costumn"},
    {name:"Covered in Plants"},
    {name:"Creepy Kid"},
    {name:"Cthulhu"},
    {name:"Cyclops"},
    {name:"Death"},
    {name:"Deer"},
    {name:"Devil"},
    {name:"Dolphin"},
    {name:"Doppelganger"},
    {name:"Dragon"},
    {name:"Dr Jekyll & Mr Hyde"},
    {name:"Dullahan"},
    {name:"El Sulbón"},
    {name:"Elder God"},
    {name:"Electric Spirit"},
    {name:"Empty Eye Sockets"},
    {name:"Evil Overlord"},
    {name:"Exposed Organs"},
    {name:"Eyeball Plant"},
    {name:"Eye Stalks"},
    {name:"Fairy"},
    {name:"Fish Humanoid"}, 
    {name:"Flaming Skull"},
    {name:"Flatwoods Monster"},
    {name:"The Fly"},
    {name:"Fortune Teller"},
    {"Frankenstein"},
    {"Freak Show Attraction"},
    {"From Outerspace"},
    {"Gargoyle"},
    {"Ghost"},
    {"Glowing"},
    {"Gnoll"},
    {"Goatman"},
    {"Golem"},
    {"Greedy"},
    {"Gremlin"},
    {"Griffin"},
    {"Hairy"},
    {"Harpy"},
    {"Hastur"},
    {"Haunted Armor"},
    {"Haunted Tree"},
    {"Haunted Vehicle"},
    {"Headless Horseman"},
    {"Heart"},
    {"Hellhound"},
    {"Hell’s Cook"},
    {"Hide-Behind"},
    {"Hitchhiker"},
    {"Hocus (Witchs Hat)"},
    {"Homunculus"},
    {"Horns"},
    {"Horror Host"},
    {"Horseman of the Apocalypse"},
    {"Insect"},
    {"Invisible"},
    {"Iron Maiden"},
    {"Jabberwocky"},
    {"Jarjacha"},
    {"Jersey Devil"},
    {"Jiang-shi"},
    {"Kaiju"},
    {"Kappa"},
    {"Karakasa"},
    {"Killer"},
    {"Kitsune"},
    {"Kobold"},
    {"Kraken"},
    {"Krampus"},
    {"La Llorona"},
    {"Living Location"},
    {"Living Shadow"},
    {"Living Statue"},
    {"Loch Ness Monster"},
    {"Long"},
    {"Lovers"},
    {"Lure"},
    {"Mad Scientist"},
    {"Maneating Plant"},
    {"Manticore"},
    {"Mapinguari"},
    {"Mimic"},
    {"Minotaur"},
    {"Mole Men"},
    {"Moloch"},
    {"Monster Biker"},
    {"Moon"},
    {"Moth Man"},
    {"Mummy"},
    {"Mushroom Creature"},
    {"Naga"},
    {"Necromancer"},
    Nervous System,
    Nuckelavee,
    Old Cartoon,
    Oni,
    Owl,
    Painting,
    Pandora’s Box,
    Parasite,
    Phantom of the Opera,
    Pig,
    Plague Doctor,
    {"Pocus (Witches Cauldron)"},
    Pollution Monster,
    Poltergeist,
    Possessed Doll,
    Pumpkin,
    Rat,
    Raven/Crow,
    Rawhead and Bloody Bones,
    Robot,
    Roundabout Mouth,
    Scarecrow,
    Sea Monster,
    Shark,
    Sharp Claws,
    Sirenhead,
    Skeleton,
    Slenderman,
    Slime,
    Slit Mouth Woman,
    Smile Dog,
    Spider,
    Spring Heel Jack,
    Stego Spines,
    Stingy Jack,
    Succubus/Inccubus,
    Swamp Creature,
    Sweet Fiends,
    Tentacles,
    Test Tube Creature,
    Toad,
    Toilet Monster,
    Too Many Eyes,
    Too Many Teeth,
    Troll,
    Tsuchinoko,
    Two Headed,
    Umi-Bozu,
    Vampire,
    Voodoo Doll,
    Walking Head,
    Werewolf,
    Will-o’-the-Wisp,
    Witch,
    Worm,
    Yog-Sothoth,
    Yokai,
    Zombie,]

function random(prompts) {
    let n = Math.floor(Math.random() * (prompts.length))
    console.log(n)
    document.getElementById("prompt").innerHTML=prompts[n].name
    document.getElementById("Description").innerHTML=prompts[n].description
}
